### ISSUE TITLE
项目的静态资源导入有问题

### ISSUE THREAD

**Issue by chen645800876** [bojiangzhou/lyyzoo-ssms#3]
![image](https://user-images.githubusercontent.com/24761804/51363847-cfbbd480-1b14-11e9-9381-43f397afe79d.png)

**Comment by DoctorWhoYX** [comment]
请问你解决这个问题没有？怎么解决的？

**Comment by mi78108** [comment]
Bug  
 出在过滤器里边，设置返回类型。重写或注释都可以。

**Comment by yansheng836** [comment]
为什么不用外部浏览器进行访问？

**Comment by namelucky** [comment]
请问这个是如何解决的呢
